### ISSUE TITLE
Support For Excluding Certain Repos

### ISSUE THREAD

**Issue by philnielsen** [akyoto/mgit#1]
Hey! Really cool little tool, one feature request (also I can try and take a look at making a PR, but wanted to get interest before I coded it), but any interest in adding some way to exclude repos from `mgit -run`? 

Right now I'm just moving them out of the way real quick and running but it would be sweet if we can a config file or flag to exclude a repo.

Something like `mgit -e "some-repo-name" -run "cat file.txt"` is what I had in mind. Adding a `.mgit` config file that listed all of the repos to exclude from that directory would be another option.

`.mgit`
```yml
excluded:
  some-repo
  some-other-repo
```

Let me know if there is interest!

**Comment by akyoto** [comment]
Sounds like a good idea!

I would personally prefer the command line flags approach, as we already have a lot of config file noise from CI, testing etc.

Accidentally commiting a `.mgit` file can potentially also cause pain for other developers on a team without them actually knowing it.
